spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digitals
    username: digitals
    password: digitals
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect